String css =
"<style>#file-input,input {width: 100%;height: 100px;border-radius: 5px;margin: 10px auto;font-size: 16px}input {background: #fff;border: 0;padding: 0 15px}body {background: #1a1a1a;font-family: sans-serif;font-size: 14px;color: #FdFdFd}#file-input {padding: 0;border: 2px solid #ddd;line-height: 45px;text-align: left;display: block;cursor: pointer}#bar,#prgbar {background-color: #4d4d4d;border-radius: 15px}#bar {background-color: #4cdebc;width: 0%;height: 15px}form {background: #1f1f1f;max-width: 300px;margin: 80px auto;padding: 30px;border-radius: 5px;text-align: center}.btn {background: #4a4a4a;color: #FFFFFF;cursor: pointer}</style>";
 
String loginIndex =
"<form name='loginForm'>"
"<h2>OTA login</h2>"
"<input name=userid placeholder='Username'> "
"<input name=pwd placeholder='Password' type=Password> "
"<input type=submit onclick=check(this.form) class=btn value=Login></form>"
"<script>"
    "function check(form)"
    "{"
    "if(form.userid.value=='admin' && form.pwd.value=='admin')"
    "{"
    "window.open('/serverIndex')"
    "}"
    "else"
    "{"
    " alert('Error Password or Username')/*displays error message*/"
    "}"
    "}"
"</script>" + css;
 
String serverIndex =
 "<script src='https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>"
 "<form method='POST' action='#' enctype='multipart/form-data' id='upload_form'>"
 "<input type='file' name='update'>"
 "<input type='submit' value='Update'>"
 "<div id='prg'>0%</div>"
 "<div id='prgbar'><div id='bar'></div></div></form>"
 "<script>"
  "$('form').submit(function(e){"
  "e.preventDefault();"
  "var form = $('#upload_form')[0];"
  "var data = new FormData(form);"
  " $.ajax({"
  "url: '/update',"
  "type: 'POST',"
  "data: data,"
  "contentType: false,"
  "processData:false,"
  "xhr: function() {"
  "var xhr = new window.XMLHttpRequest();"
  "xhr.upload.addEventListener('progress', function(evt) {"
  "if (evt.lengthComputable) {"
  "var per = evt.loaded / evt.total;"
  "$('#prg').html('Running ' + Math.round(per*100) + '%');"
  "$('#bar').css('width',Math.round(per*100) + '%');"
  "}"
  "}, false);"
  "return xhr;"
  "},"
  "success:function(d, s) {"
  "console.log('success!')"
 "},"
 "error: function (a, b, c) {"
 "}"
 "});"
 "});"
 "</script>" + css;